# EDA: Diagnosing Diabetes

In this project, you'll imagine you are a data scientist interested in exploring data that looks at how certain diagnostic factors affect the diabetes outcome of women patients.

You will use your EDA skills to help inspect, clean, and validate the data.

**Note**: This [dataset](https://www.kaggle.com/uciml/pima-indians-diabetes-database) is from the National Institute of Diabetes and Digestive and Kidney Diseases. It contains the following columns:

- `Pregnancies`: Number of times pregnant
- `Glucose`: Plasma glucose concentration per 2 hours in an oral glucose tolerance test
- `BloodPressure`: Diastolic blood pressure
- `SkinThickness`: Triceps skinfold thickness
- `Insulin`: 2-Hour serum insulin
- `BMI`: Body mass index
- `DiabetesPedigreeFunction`: Diabetes pedigree function
- `Age`: Age (years)
- `Outcome`: Class variable (0 or 1)

Let's get started!

## Initial Inspection

1. First, familiarize yourself with the dataset [here](https://www.kaggle.com/uciml/pima-indians-diabetes-database).

   Look at each of the nine columns in the documentation.
   
   What do you expect each data type to be?

Expected data type for each column:

- `Pregnancies`: 
- `Glucose`: 
- `BloodPressure`: 
- `SkinThickness`: 
- `Insulin`: 
- `BMI`: 
- `DiabetesPedigreeFunction`: 
- `Age`: 
- `Outcome`:

2. Next, let's load in the diabetes data to start exploring.

   Load the data in a variable called `diabetes_data` and print the first few rows.
   
   **Note**: The data is stored in a file called `diabetes.csv`.

In [3]:
import pandas as pd
import numpy as np

# load in data
diabetes_data = pd.read_csv('diabetes.csv')
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

3. How many columns (features) does the data contain?

In [4]:
# print number of columns
print(len(diabetes_data.columns))

9

4. How many rows (observations) does the data contain?

In [5]:
# print number of rows
print(len(diabetes_data.index))

768

## Further Inspection

5. Let's inspect `diabetes_data` further.

   Do any of the columns in the data contain null (missing) values?

In [6]:
# find whether columns contain null values
diabetes_data.isnull().values.any()

False

6. If you answered no to the question above, not so fast!

   While it's technically true that none of the columns contain null values, that doesn't necessarily mean that the data isn't missing any values.
   
   When exploring data, you should always question your assumptions and try to dig deeper.
   
   To investigate further, calculate summary statistics on `diabetes_data` using the `.describe()` method.

In [7]:
# perform summary statistics
diabetes_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

7. Let's see if we can get a more accurate view of the missing values in the data.

In [23]:
# replace instances of 0 with NaN
diabetes_data[['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']] = diabetes_data[['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']].replace(0, np.NaN)
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

8. Next, check for missing (null) values in all of the columns just like you did in Step 5.

    Now how many missing values are there?

In [9]:
# find whether columns contain null values after replacements are made
diabetes_data.isnull().values.sum()

652

9. Let's take a closer look at these rows to get a better idea of _why_ some data might be missing.

    Print out all the rows that contain missing (null) values.

In [17]:
# print rows with missing values
is_null_temp = diabetes_data[diabetes_data.isnull().any(axis=1)]
is_null_temp.head(100)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0
9,8,125.0,96.0,NaN,NaN,NaN,0.232,54,1
10,4,110.0,92.0,NaN,NaN,37.6,0.191,30,0
11,10,168.0,74.0,NaN,NaN,38.0,0.537,34,1
12,10,139.0,80.0,NaN,NaN,27.1,1.441,57,0
15,7,100.0,NaN,NaN,NaN,30.0,0.484,32,1
17,7,107.0,74.0,NaN,NaN,29.6,0.254,31,1
21,8,99.0,84.0,NaN,NaN,35.4,0.388,50,0
22,7,196.0,90.0,NaN,NaN,39.8,0.451,41,1
23,9,119.0,80.0,35.0,NaN,29.0,0.263,29,1
26,7,147.0,76.0,NaN,NaN,39.4,0.257,43,1
29,5,117.0,92.0,NaN,NaN,34.1,0.337,38,0
30,5,109.0,75.0,26.0,NaN,36.0,0.546,60,0
33,6,92.0,92.0,NaN,NaN,19.9,0.188,28,0
34,10,122.0,78.0,31.0,NaN,27.6,0.512,45,0
36,11,138.0,76.0,NaN,NaN,33.2,0.420,35,0
37,9,102.0,76.0,37.0,NaN,32.9,0.665,46,1
38,2,90.0,68.0,42.0,NaN,38.2,0.503,27,1
41,7,133.0,84.0,NaN,NaN,40.2,0.696,37,0
42,7,106.0,92.0,18.0,NaN,22.7,0.235,48,0
44,7,159.0,64.0,NaN,NaN,27.4,0.294,40,0
45,0,180.0,66.0,39.0,NaN,42.0,1.893,25,1
46,1,146.0,56.0,NaN,NaN,29.7,0.564,29,0
47,2,71.0,70.0,27.0,NaN,28.0,0.586,22,0
48,7,103.0,66.0,32.0,NaN,39.1,0.344,31,1
49,7,105.0,NaN,NaN,NaN,NaN,0.305,24,0
55,1,73.0,50.0,10.0,NaN,23.0,0.248,21,0
58,0,146.0,82.0,NaN,NaN,40.5,1.781,44,0
60,2,84.0,NaN,NaN,NaN,NaN,0.304,21,0
61,8,133.0,72.0,NaN,NaN,32.9,0.270,39,1
62,5,44.0,62.0,NaN,NaN,25.0,0.587,36,0
64,7,114.0,66.0,NaN,NaN,32.8,0.258,42,1
65,5,99.0,74.0,27.0,NaN,29.0,0.203,32,0
66,0,109.0,88.0,30.0,NaN,32.5,0.855,38,1
67,2,109.0,92.0,NaN,NaN,42.7,0.845,54,O
72,13,126.0,90.0,NaN,NaN,43.4,0.583,42,1
74,1,79.0,75.0,30.0,NaN,32.0,0.396,22,0
75,1,NaN,48.0,20.0,NaN,24.7,0.140,22,0
76,7,62.0,78.0,NaN,NaN,32.6,0.391,41,0
77,5,95.0,72.0,33.0,NaN,37.7,0.370,27,0
78,0,131.0,NaN,NaN,NaN,43.2,0.270,26,1
79,2,112.0,66.0,22.0,NaN,25.0,0.307,24,0
80,3,113.0,44.0,13.0,NaN,22.4,0.140,22,0
81,2,74.0,NaN,NaN,NaN,NaN,0.102,22,0
83,0,101.0,65.0,28.0,NaN,24.6,0.237,22,0
84,5,137.0,108.0,NaN,NaN,48.8,0.227,37,1
86,13,106.0,72.0,54.0,NaN,36.6,0.178,45,0
89,1,107.0,68.0,19.0,NaN,26.5,0.165,24,0
90,1,80.0,55.0,NaN,NaN,19.1,0.258,21,0
93,4,134.0,72.0,NaN,NaN,23.8,0.277,60,1
96,2,92.0,62.0,28.0,NaN,31.6,0.130,24,0
100,1,163.0,72.0,NaN,NaN,39.0,1.222,33,1
101,1,151.0,60.0,NaN,NaN,26.1,0.179,22,0
102,0,125.0,96.0,NaN,NaN,22.5,0.262,21,0
104,2,85.0,65.0,NaN,NaN,39.6,0.930,27,0
106,1,96.0,122.0,NaN,NaN,22.4,0.207,27,0
113,4,76.0,62.0,NaN,NaN,34.0,0.391,25,0
115,4,146.0,92.0,NaN,NaN,31.2,0.539,61,1
116,5,124.0,74.0,NaN,NaN,34.0,0.220,38,1
117,5,78.0,48.0,NaN,NaN,33.7,0.654,25,0
118,4,97.0,60.0,23.0,NaN,28.2,0.443,22,0
121,6,111.0,64.0,39.0,NaN,34.2,0.260,24,0
123,5,132.0,80.0,NaN,NaN,26.8,0.186,69,0
124,0,113.0,76.0,NaN,NaN,33.3,0.278,23,1
129,0,105.0,84.0,NaN,NaN,27.9,0.741,62,1
131,9,122.0,56.0,NaN,NaN,33.3,1.114,33,1
133,8,84.0,74.0,31.0,NaN,38.3,0.457,39,0
138,0,129.0,80.0,NaN,NaN,31.2,0.703,29,0
140,3,128.0,78.0,NaN,NaN,21.1,0.268,55,0
141,5,106.0,82.0,30.0,NaN,39.5,0.286,38,0
143,10,108.0,66.0,NaN,NaN,32.4,0.272,42,1
145,0,102.0,75.0,23.0,NaN,NaN,0.572,21,0
146,9,57.0,80.0,37.0,NaN,32.8,0.096,41,0
148,5,147.0,78.0,NaN,NaN,33.7,0.218,65,0
149,2,90.0,70.0,17.0,NaN,27.3,0.085,22,0
151,4,114.0,65.0,NaN,NaN,21.9,0.432,37,0
154,8,188.0,78.0,NaN,NaN,47.9,0.137,43,1
155,7,152.0,88.0,44.0,NaN,50.0,0.337,36,1
160,4,151.0,90.0,38.0,NaN,29.7,0.294,36,0
163,2,100.0,64.0,23.0,NaN,29.7,0.368,21,0
164,0,131.0,88.0,NaN,NaN,31.6,0.743,32,1
166,3,148.0,66.0,25.0,NaN,32.5,0.256,22,O
167,4,120.0,68.0,NaN,NaN,29.6,0.709,34,0
168,4,110.0,66.0,NaN,NaN,31.9,0.471,29,0
170,6,102.0,82.0,NaN,NaN,30.8,0.180,36,1
172,2,87.0,NaN,23.0,NaN,28.9,0.773,25,0
176,6,85.0,78.0,NaN,NaN,31.2,0.382,42,0
178,5,143.0,78.0,NaN,NaN,45.0,0.190,47,0
179,5,130.0,82.0,NaN,NaN,39.1,0.956,37,1
180,6,87.0,80.0,NaN,NaN,23.2,0.084,32,0
182,1,NaN,74.0,20.0,23.0,27.7,0.299,21,0
183,5,73.0,60.0,NaN,NaN,26.8,0.268,27,0
184,4,141.0,74.0,NaN,NaN,27.6,0.244,40,0
185,7,194.0,68.0,28.0,NaN,35.9,0.745,41,1
190,3,111.0,62.0,NaN,NaN,22.6,0.142,21,0
192,7,159.0,66.0,NaN,NaN,30.4,0.383,36,1

10. Go through the rows with missing data. Do you notice any patterns or overlaps between the missing data?

11. Next, take a closer look at the data types of each column in `diabetes_data`.

    Does the result match what you would expect?

In [14]:
# print data types using .info() method
diabetes_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   763 non-null    float64
 2   BloodPressure             733 non-null    float64
 3   SkinThickness             541 non-null    float64
 4   Insulin                   394 non-null    float64
 5   BMI                       757 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    object
dtypes: float64(6), int64(2), object(1)
memory usage: 54.1+ KB

12. To figure out why the `Outcome` column is of type `object` (string) instead of type `int64`, print out the unique values in the `Outcome` column.

In [18]:
# print unique values of Outcome column
print(diabetes_data.Outcome.unique())

['1' '0' 'O']

## Next Steps:

13. Congratulations! In this project, you saw how EDA can help with the initial data inspection and cleaning process. This is an important step as it helps to keep your datasets clean and reliable.

    Here are some ways you might extend this project if you'd like:
    - Use `.value_counts()` to more fully explore the values in each column.
    - Investigate other outliers in the data that may be easily overlooked.
    - Instead of changing the `0` values in the five columns to `NaN`, try replacing the values with the median or mean of each column.